type:feature:
  - head-branch: ['^feature', 'feature']

type:bug:
  - head-branch: ['^bug', 'bug']

type:improvement:
  - head-branch: ['^improve', 'improve']

type:chore:
  - head-branch: ['^chore', 'chore']

type:release:
  - head-branch: ['^release', 'release']

# Add build deployment method to PRs that increment the runtime version
eas-build-all:develop:
  - all:
      - base-branch: 'main'
      - changed-files:
          - any-glob-to-any-file: ['eas.json', 'src/assets/**/*']
