type:feature:
  - head-branch: ['^feature', 'feature']

type:bug:
  - head-branch: ['^bug', 'bug']

type:improvement:
  - head-branch: ['^improve', 'improve']

type:chore:
  - head-branch: ['^chore', 'chore']

type:release:
  - head-branch: ['^release', 'release']

# Add build deployment method to PRs that increment the runtime version
deploy:build:
  - all:
      - base-branch: 'main'
      - changed-files:
          - any-glob-to-any-file: ['package.json', 'app.json', 'eas.json', 'src/assets/**/*']

# Add deploy method to PRs that change the typescript source code
deploy:update:
  - all:
      - base-branch: 'main'
      - changed-files:
          - any-glob-to-any-file: 'src/**/*'
          - all-globs-to-all-files: ['!package.json', '!app.json', '!eas.json', '!src/assets/**/*']
