name: 🐞 Bug Report
description: File a bug or issue report.
title: '[Bug] '
labels: ['type:bug']
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Bug prevents use of the app
        - High - Bug causes features to not work as expected
        - Medium - Bug has a workaround
        - Low - Bug does not affect functionality, but should be fixed
      default: 2
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: On what platform are you experiencing this bug?
      multiple: true
      options:
        - iOS
        - Android
    validations:
      required: true

  - type: input
    id: platform-version
    attributes:
      label: Platform Version
      description: What version of the platform are you running?
      placeholder: iOS 18.1

  - type: input
    id: version
    attributes:
      label: App version
      description: What version of the app are you running? (Check the bottom of the menu)
      placeholder: 1.0.2

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clear and concise description of the problem. Attach screenshots if needed, and include any errors you see.
      placeholder: When I do this, that happens.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: Clear and concise description of what you think should happen.
      placeholder: When I do this, that should happen.

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Minimal steps neded for the problem to occur.
      placeholder: |
        1. Open the app
        2. Open the menu
        3. Click on the button...
