name: 🚀 Feature Request
description: Suggest a new feature.
title: '[Feature Request] '
labels: ['type:feature']
body:
  - type: markdown
    attributes:
      value: |
        *Please add an appropriate title for this feature request.*

  - type: dropdown
    attributes:
      label: Confirmations
      multiple: true
      options:
        - I have checked that this feature is not already requested or implemented
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Description
      description: Clear and concise description of the feature or missing capability. Attach screenshots if needed, and explain your own use case.
      placeholder: As a user, I want to be able to...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation
      description: How would you implement this feature? If you have an idea, please share it.
      placeholder: Step 1, do this. Step 2, do that.

  - type: markdown
    attributes:
      value: |
        Please add the appropriate platform and priority labels to the issue.
        > Thank you for your feature request! 🚀
