const LocalizationDefaults = {
  add_players: 'Add players',
  app_name: 'Brisen',
  categories_subtitle: 'Enable or disable categories.',
  categories: 'Categories',
  category: 'Category',
  change_language: 'Change language',
  clear: 'Clear',
  coming_soon_about: 'These packs are coming soon!',
  coming_soon_msg: 'This pack wil be available {0}!',
  coming_soon_title: 'Coming soon',
  copied_to_clipboard: 'Copied to clipboard',
  error_alert_title: 'Oops 😨',
  icon_info_purchase: 'Subscribe to Brisen+ to unlock these packs!',
  icon_info_restart: 'This button restarts the game, letting you play your favorite packs again!',
  icon_info_selected:
    'The pack is selected! When scrolling, cards from this pack will be drawn. Drawn cards will not be redrawn until the game is restarted.',
  in_days: 'in {0} days',
  in_one_month: 'in one month',
  in_one_week: 'in one week',
  in_x_weeks: 'in {0} weeks',
  info_subtitle: 'What does the little icons mean?',
  info: 'Information',
  leaving_soon_about: 'These packs are leaving soon! Try them out before they disappear!',
  loading: 'Loading content…',
  manage_subscriptions: 'My subscription',
  out_of_cards: "That's all folks! 🤷🏽‍♂️ Select a new pack to keep playing!",
  pack_unplayable_msg: 'More players or categories required',
  pack_unplayable_title: 'To play this pack, you need to add more players or remove some category filters.',
  packs_subtitle: 'Select one or more packs to start a game!',
  packs: 'Packs',
  player_exists_msg: 'Try again with another name',
  player_exists_title: 'This player already exists',
  players_subtitle: 'Add players to personalize the experience!',
  players: 'Players',
  purchase_complete_msg: 'Thank you! 🤩 Enjoy full access to everything in Brisen! 🥳',
  purchase_complete_title: '🎉 Wohoo! 🎉',
  purchase_error_msg: 'Could not complete the purchase 🥵 Try again later',
  restart_game: 'Restart',
  restore_completed_msg_fail: "Seems like you don't have any active subscriptions 😳",
  restore_completed_msg_success: 'Your subscription was restored! 🎉',
  restore_completed_title: '✅ Restore completed',
  restore_error_msg: 'Failed to restore your subscription 🥵',
  select_pack: 'Add players and select a pack to get the party started! 🎉',
  settings: 'Settings',
  share_app: 'Share the app',
  share_message: 'Check out Brisen! 🍻',
  start_game: 'Play',
  today: 'Today',
  tomorrow: 'Tomorrow',
  try_again: 'Try again',
  version: 'Version',
}

export default LocalizationDefaults
