name: Check labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "type:" label
        run: |
          echo "${{ github.event.pull_request.labels.*.name }}"
          exit 1
