name: Check labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "type:" label
        run: |
          if ! echo "${{ github.event.pull_request.labels.*.name }}" | grep -q 'type:'; then
            echo "Error: Pull request is missing a 'type:' label."
            exit 1
          fi

      - name: Check for "status:" label
        run: |
          if ! echo "${{ github.event.pull_request.labels.*.name }}" | grep -q 'status:'; then
            echo "Error: Pull request is missing a 'status:' label."
            exit 1
          fi
