name: Check labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Print labels array
        run: |
          if [[ ${{ toJson(github.event.pull_request.labels.*.name) }} == *type:* ]]; then
            echo "Type label found"
          else
            echo "Type label not found"
            exit 1
          fi
