name: Expo doctor

on:
  pull_request:
    branches:
      - main
      - develop
      - release/**
    paths:
      - src/**
      - app.json
      - eas.json
      - package.json
      - package-lock.json
      - .github/workflows/doctor.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
      - name: 📦 Install dependencies
        run: npm ci

      - name: 💊 Run doctor
        run: npx expo-doctor
