name: ✅ PR Summary

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types:
      - created

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  summarize:
    name: 🐰 CodeRabbit summary
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
          openai_heavy_model: gpt-3.5-turbo
          summarize: |
            Provide your final response in markdown with the following content:

            - **Summary**: A high-level summary of the overall change instead of specific files, within 50 words.
            - **Changes**: A summary of changes made to each file. Format this by having each file name in H2 and the changes in a markdown list.
            - **Review**: A markdown list of suggestions to specific changes that can be made to improve the code quality. Consider both specific code-level suggestions and high-level architectural suggestions. Only add this section if the suggestions have significant impact on the code quality.

            Avoid additional commentary as this summary will be added as a comment on the GitHub pull request. Use the titles "Summary", "Changes", and "Review" and they must be H1. Only include the "Reivew" section if the suggestions have significant impact on the code quality.
