name: Expo Update Release

on:
  push:
    branches:
      - release/**
    paths:
      - src/**
      - app.json
      - eas.json
      - package.json
      - package-lock.json
      - .github/workflows/update_release.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    environment: Release
    env:
      EXPO_PUBLIC_ENV: release
      EXPO_PUBLIC_SB_URL_DEV: ${{ vars.SUPABASE_URL_DEV }}
      EXPO_PUBLIC_SB_ANON_DEV: ${{ secrets.SUPABASE_ANON_DEV }}
      EXPO_PUBLIC_RC_KEY_APPLE: ${{ secrets.REVENUECAT_APPLE }}
      EXPO_PUBLIC_RC_KEY_GOOGLE: ${{ secrets.REVENUECAT_GOOGLE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: Get details
        id: get-details
        run: |
          echo "::set-output name=branch::$(echo "${{ github.ref }}" | sed 's|refs/heads/||')"
          echo "::set-output name=message::$(echo "${{ github.event.head_commit.message }}" | head -n 1)"

      - name: 🚀 Push release update
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --channel release --branch "${{ steps.get-details.outputs.branch }}" --message "${{ steps.get-details.outputs.message }}"
