name: Expo Update Preview

on:
  pull_request:
    branches:
      - develop
      - release/**
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: write
    env:
      EXPO_PUBLIC_ENV: preview
      EXPO_PUBLIC_SB_URL_DEV: ${{ vars.SUPABASE_URL_DEV }}
      EXPO_PUBLIC_SB_ANON_DEV: ${{ secrets.SUPABASE_ANON_DEV }}
      EXPO_PUBLIC_RC_KEY_APPLE: ${{ secrets.REVENUECAT_APPLE }}
      EXPO_PUBLIC_RC_KEY_GOOGLE: ${{ secrets.REVENUECAT_GOOGLE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Push PR preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --channel preview --message ${{ github.head_ref }}
