name: Expo Update Production

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - app.json
      - eas.json
      - package.json
      - package-lock.json
      - .github/workflows/update_prod.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-preview:
    runs-on: ubuntu-latest
    environment: production
    env:
      EXPO_PUBLIC_SB_URL: ${{ vars.SUPABASE_URL_DEV }}
      EXPO_PUBLIC_SB_ANON: ${{ secrets.SUPABASE_ANON_DEV }}
      EXPO_PUBLIC_RC_KEY_APPLE: ${{ secrets.REVENUECAT_APPLE }}
      EXPO_PUBLIC_RC_KEY_GOOGLE: ${{ secrets.REVENUECAT_GOOGLE }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: Get first line of commit message
        id: get-message
        run: echo "::set-output name=message::$(echo "${{ github.event.head_commit.message }}" | head -n 1)"

      - name: 🚀 Push production update
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --channel production --message "${{ steps.get-message.outputs.message }}"
