name: Deploy Expo Preview

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
    paths:
      - src/**
      - app.json
      - eas.json
      - package.json
      - package-lock.json
      - .github/workflows/publish_update.yml
  push:
    branches:
      - develop
    paths:
      - src/**
      - app.json
      - eas.json
      - package.json
      - package-lock.json
      - .github/workflows/publish_update.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      EXPO_PUBLIC_SB_URL: ${{ vars.SUPABASE_URL_DEV }}
      EXPO_PUBLIC_SB_ANON: ${{ secrets.SUPABASE_ANON_DEV }}
      EXPO_PUBLIC_RC_KEY_APPLE: ${{ secrets.REVENUECAT_APPLE }}
      EXPO_PUBLIC_RC_KEY_GOOGLE: ${{ secrets.REVENUECAT_GOOGLE }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: Get branch name
        id: get-branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "::set-output name=branch::$(echo "${{ github.head_ref }}" | head -n 1)"
          else
            echo "::set-output name=branch::$(echo "${{ github.ref }}" | head -n 1)"
          fi

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --channel develop --message ${{ steps.get-branch.outputs.branch }}
