name: Expo Update Develop

on:
  push:
    branches:
      - develop
    paths:
      - src/**
      - app.config.ts
      - eas.json
      - package.json
      - package-lock.json
      - .github/workflows/update_develop.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    environment: Develop
    env:
      EXPO_PUBLIC_ENV: develop
      EXPO_PUBLIC_SB_URL_DEV: ${{ vars.SUPABASE_URL_DEV }}
      EXPO_PUBLIC_SB_ANON_DEV: ${{ secrets.SUPABASE_ANON_DEV }}
      EXPO_PUBLIC_RC_KEY_APPLE: ${{ secrets.REVENUECAT_APPLE }}
      EXPO_PUBLIC_RC_KEY_GOOGLE: ${{ secrets.REVENUECAT_GOOGLE }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: Get first line of commit message
        id: get-message
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "::set-output name=message::$(echo "${{ github.event.head_commit.message }}" | head -n 1)"
          else
            echo "::set-output name=message::$(echo "${{ github.ref }}" | sed 's|refs/heads/||')"
          fi

      - name: 🚀 Push develop update
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --channel develop --message "${{ steps.get-message.outputs.message }}"
